# Site settings
title: CBA Cloud
description: "CBA Cloud - Your Business Solution"
baseurl: "" # Keep empty to serve from the root
url: "http://127.0.0.1:4000" # Localhost during development

# Language settings
default_lang: "en" # Default language
languages: ["en", "pt"] # Supported languages

# Build settings
markdown: kramdown
sass:
  indentWidth: 4
  style: compressed
  precision: 10

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclusions (files Jekyll should ignore)
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md
