
name: 🚀 Deploy Jekyll to Remote Server

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: master

      - name: 🧼 Remove .git folder before SCP
        run: rm -rf .git

      - name: 🚀 Copy files to Synology NAS via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NAS_HOST }}
          username: ${{ secrets.NAS_USER }}
          key: ${{ secrets.NAS_SSH_KEY }}
          port: ${{ secrets.NAS_PORT }}
          source: "."
          target: "~/cba-website"
          overwrite: true
          rm: true

      - name: 💻 SSH into NAS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NAS_HOST }}
          username: ${{ secrets.NAS_USER }}
          key: ${{ secrets.NAS_SSH_KEY }}
          port: ${{ secrets.NAS_PORT }}
          script: |
            cd ~/cba-website
            sudo /usr/local/bin/docker-compose down
            sudo /usr/local/bin/docker-compose build
            sudo /usr/local/bin/docker-compose up -d
